### ISSUE TITLE
The thin line missing around windows

### ISSUE THREAD

**Issue by RobertBoganKang** [B00merang-Project/Windows-10-Dark#10]
For windows 10 theme, there is a light thin line around it so that we can see where is the windows. 
If there is no lines around windows, we cannot see the edge of windows since shadows under windows are also dark colors.

**Comment by Elbullazul** [comment]
it's there, but it's a dark shadow inherited from the light variant. Will fix

**Comment by RobertBoganKang** [comment]
thanks, the bug is missing now!

**Comment by RobertBoganKang** [comment]
I find another bug, when maximize, the buttons at top-right corner are brighter than the title bar, and the bottom thin border is still there.

**Comment by RobertBoganKang** [comment]
and the slider in the scroll bar (on the right side of windows, or other sliders, I cannot see it), the color are similar, in windows darker theme, it is a little bit brighter than the scroll bar.

**Comment by Elbullazul** [comment]
I have reworked the titlebar and scrollbar, should be fixed

**Comment by RobertBoganKang** [comment]
1. the small slider (cinnamon nemo file manager fight bottom corner) still cannot see.
2. when maximize, the right top corner buttons are slightly brighter.

**Comment by Elbullazul** [comment]
can you post a picture of the issue? all seems ok to me

**Comment by RobertBoganKang** [comment]
in Windows 10 Dark: ![win-10-dark-3](https://raw.githubusercontent.com/B00merang-Project/gallery/master/Windows%2010%20Dark%20(3).png)
the progress indicator or blue or gray slider are in the dark tray, which is almost invisible for me, it should be a little bit brighter than the background such that we can see it.
The edge of button or slider should be more contrast with something around it so that we can easily see where it is, so with it, we can work faster.
![win-10-acrylic-dark-3](https://raw.githubusercontent.com/B00merang-Project/gallery/master/Windows%2010%20Acrylic%20Dark%20(3).png) this one (Windows 10 Acrylic Dark) looks great to me now.
in cinnamon, when maximize, the titlebar on the top will change color, however the top right buttons remains the original color. This bug appears also in windows 10, windows 10-acrylic dark...

**Comment by Elbullazul** [comment]
ok, I'll rework the through widgets to improve visual difference on dark themes.

the titlebar coloring is indeed a bug, it should be easy to fix

**Comment by Elbullazul** [comment]
related: [#149](https://github.com/B00merang-Project/Windows-10/issues/149)

120924e fixex the titlebar issue and 1513559 fixes the scale and progressbar through coloring. Also improves contrast with borders.
